"""Constants used by pyTibber"""

__version__ = "0.19.0"

RESOLUTION_HOURLY = "HOURLY"
RESOLUTION_DAILY = "DAILY"
RESOLUTION_WEEKLY = "WEEKLY"
RESOLUTION_MONTHLY = "MONTHLY"
RESOLUTION_ANNUAL = "ANNUAL"
