sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install tox flake8 pylint gql aiohttp==2.2.5 async_timeout==1.4.0
language: python
script:
- flake8 Tibber --max-line-length=120
- pylint Tibber --max-line-length=120
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: Hv/QlMcwIyRwekECJP3M+6GkEA9Ja4tjwyE4f5TIjMEwHAiZMGCRckSYS/3+6xZa7JJxKLkzfCxoyOMdN+1+88Pj9NEAonarpPit4pqTnAiDePcpEgIf5aOGaRVorls1o9FDrwxfPdu9tgfx25h6H6d7n7/sqLtttMoArT3mnE5fobTZZ+mNRodcYRrEvUBfnK0sxBfl8gLopnJFzM47LP0c/4UzhZ6ccUP63hDIFsaV8gh2QU7xStaUOBXMmaw/0K/U25MawtRa4Sk1Ht3I5X1atspBVi4x1KeEe2cd85VJW083AfsKs4Qw+myhHRi6anDf6s01zTs6LCaBQw0azw3MTabz4PU4nDBt+mpZDyf0vG3KeIT7xM8Bo++IzklFIKZqexDrOdrAlrb9/hUqXxn6EW2/7LMWIP0aGKS1Je+ucbgHVClEdCli9PsAXK4mI6moYlefXjqHgntm2s42kIy+T6dDU6hPKYs/GvFbLd8yJjMxJVVLKKn8ziW0XFyGkr6e9PCYdIn+1R5/kr4qFF28gR0Njd0VMWbWhgOk5KHVfdmLzTtJt38TkyDSyMCLE/0lg3mstSjizgrVmKhZG1bJPu7UtDWKLXJuDT4RIDcp1gnSTmQeRHv85+0nEZqHtl6E5zVCaEwx+L46VjQByhKV2IJ4Re2o9Gw9yzpxvSc=
  on:
    tags: true
    repo: Danielhiversen/pyTibber
