sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: 'nightly'
    env: TOXENV=py37
  - python: '3.7-dev'
    env: TOXENV=py37
  - python: '3.8-dev'
    env: TOXENV=py38

  - python: '3.5'
    env: TOXENV=lint

  allow_failures:
  - python: 'nightly'
  - python: '3.8-dev'


cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install tox coveralls
language: python
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: q/3NQ0fplbH9pcwzmqlfBv+65OECnXq+Pc/4nLdse8ekTPTm0wlkWpJySt1pxmNkaHgnlIIWg/cdvJ46LZ0EL+rUfBxqCfUBZil2arPGUTu4qddwb0S3j330O7R28XIbQhGRqvjtAeWUBfrOA5GZxg4WEozzrzQVhiXGNTXKGKStzjqJKf3rzzbPeiFwe3w68G8IS9gfSJX2zYMkvEQeMxr3JMp2S8VUn9ay1r1JCAiUCTWIBb82ZeHAXCj/lewT3kQdyAtQip/dVagzf/vqh87ItiVXAjksZII4wjII8InxRLnYY63ybn0vedOioGTJ6aAREzrlosE0uNBcbz4n4Am4CBMqEl1L2N0wZfzzNHZFdw7PaCAGcZBXvIqhSGFgrT6WxvttU9tSw5YcETV5Un1cKQXz+t10fGFlI3RlJERWziTJX1tIohFX+53V10xPp4yFtc41m+lZEBtR6WqO4+yPtn7Dl+pEvD4ewghBGPRDFZ90YzlhcJKafbl74ZzFneWvMuq7cHv5T1aoa2c+6ZSxeCaMOnuoIuQ/eHsMVIELgpLyOAkcQGNbYoMe8SYew69ZtQ5yYORyPUNKPJLQ59t8LfJPFP0FFl3LetoVlYLoo9BrdJ589D2BVlze90dblQAe2NU7aX3+wTyvn0gv+14O17PH1fIVw/L4W4Y3LD4=
  distributions: sdist bdist_wheel
  on:
    tags: true
    repo: Danielhiversen/pyTibber
    condition: "$TOXENV = py35"
    branch: master

