sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=py35
  - python: '3.6'
    env: TOXENV=py36
  - python: '3.7'
    env: TOXENV=py37
    dist: xenial
  - python: nightly
    env: TOXENV=py37
  - python: 3.8-dev
    env: TOXENV=py38
    dist: xenial
  - python: '3.6'
    env: TOXENV=lint
  allow_failures:
  - python: nightly
  - python: 3.8-dev
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install tox coveralls
language: python
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: oDp/dCt60iWqJZrTTugzyEr3AOgSrgvSpk1QYOjhHlOijvlle2gMkf2DuW0GH8nmb+FKOq0BjOG5bwioa+NMQl60hV0MOnAHu//SbTPvIKwKFJAa208X60L3d0iux54IuHOroep1+/9Xqq+LNMvn8XiWZ6a9OwBSDkw/+nkYyoZVcionJ6pm5JsWv6QygFkYIjqbeFOofs+ewAvgQxG15NHtB7w9DlicMLs9xWvrNZ0vvOdqsj2H+fsgiRjSsUrkObIumhG1LGQeT4vOZdv5SYHliZIUQcv33uVMOpivOq7OrUeVTyqsoQzCPEVTxqdnIN5rIayOfFs95+joJYp+O9xfZhHzzYbi8h7GetPufm2FBDvcCXrpeZnqknDFxNw3qwgwJO0i2oRihZMLhFjKH0VzkBP7DIFXUiKymZLBj20XN1lw8TrMfh91//oUeiBkcv9mV7MYwR/5pHU/aEpA1GIegoLNlQzk/3Q3KCmCXzpgTbc1vsxHm5QnJDWFwCW5T3MjlgX/c7EX/gGTxyqywwDKqyxqytHY0/nLlr9amdTOnYT2U2ks7NaV/zVK9vSzS1+IqqxT2lgHQFP7n3h4K2hkHlhEADA/+WO4MYYY0h2eT2xzEYEzW+r8nIsNkGAt7GlxdO1lHbRLk4EHtJ5DZujt0HpZlraoitxdGq7aFec=
  on:
    tags: true
    repo: Danielhiversen/pyTibber
    condition: "$TOXENV = py35"
    branch: master
