sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.9'
    env: TOXENV=py39
  - python: '3.8'
    env: TOXENV=py38
    dist: xenial
  - python: '3.8'
    env: TOXENV=lint
  - python: nightly
    env: TOXENV=py39
allow_failures:
  - python: nightly
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install tox coveralls
language: python
script: tox
after_success: coveralls
