sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.9'
    env: TOXENV=py39
  - python: '3.8'
    env: TOXENV=py38
    dist: xenial
  - python: '3.8'
    env: TOXENV=lint
  - python: nightly
    env: TOXENV=py39
allow_failures:
  - python: nightly
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install tox coveralls
language: python
script: tox
after_success: coveralls
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: TUPtPn/UdReAili6gTQeI8wfadr4e+VTB9MkujUMjHUNlC2vvijacd6QsJhGQiovH6doDLkPkHwoYSHPMP2IhS7kMWdFZSqrMHdS7KHfGtFagw6E/Q66E2LHpVvFQ58sEBsb1e44Vaupm01F3//h4jCnmumafBA21cA0TeF1VDhuksvaFfipegCD2UKIKd8wHhmdXZs+VBGcgQ7271f9PM0lzTB1zzssK1OgznTmlx6BFTorxe2rxB6xxbHVRnvV3H1/SokegC7sIJf6Lq9ZmKVpIajIdkOmC5IMxxte0GMdjVhhauSK1fmonb2+nyP7KyjF7bxdba8QuNy7V3ti9tNRMxw/Q0a1hhcaksUNCo1yBRvVgU4MqRc0W6BzpjVKjrZNsiD3Xjgh/T8I79Cb5vL8dtDfloHZ1Yc9g/EzQR75vCEOVNC7+Qm1CABiPnmjG9w0bBCNrU5oysxGWsJSAYYOze2Z26wMc7ZyCGYKUbKr3qypp729mWkN4Z0Ks4hBUXCHDoXJ/v9eN2j3h0lv038D7m9dFQAVZJiJ8YrWaDQ47LN3sUdxpp8idJD3ZtYsrZCwPZoyK4fF3dABA7+mb8fPviRXq20kkynLBfyJoBInlnjivwyTDX8ia77zzloSM2Iib3neSpg/iZLYjCsqzcZCiFvwNu+K/1JyIiXto1Y=
  on:
    tags: true
    repo: Danielhiversen/pyTibber
    condition: "$TOXENV = py38"
    branch: master
