sudo: false
matrix:
  fast_finish: true
  include:
  - python: '3.5'
    env: TOXENV=lint
cache:
  directories:
  - "$HOME/.cache/pip"
install:
- pip install tox flake8 pylint gql aiohttp==2.2.5 async_timeout==1.4.0
language: python
script:
- flake8 Tibber --max-line-length=120
- pylint Tibber --max-line-length=120
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: JSrvLspfFKFXJvlLvcb/Wo8S8QGhj0ByUy9lN6Sg59CL2nHfLrR9PdD9gluouOH+IlNo7q8s6fagGm8uePw/Rb4LOCCE0tZxJtI2hvIXrdxuecQ0CGHu/cnwGjmP1rehg/IHsSf67ZQc50CCL7jiu17sYg35ozwgp6FFNd0jTV6rwmY2hnpTmlUAJ2Clhur6Vep5wHqYkv6SGKS6tBFhMtDwYD2Bmp5zTscosR+ds16FCxV4nYK9BWUL2lbhoXMtQdZwQWi6d7rkXRdJwEHij6zvhc0Gq76xRCvhAtRftmMeReK9dk3TefvF0GitN85EF18+XmzvlaJeEgs8SrAzcqmYRYq0Yelqa5zV/tw649QTxX5N08Xf5yJh3UBH/5YuH2DlWGhiifiwUHNCT/lzhJff3B7ZMUZNHWZ/SgeMzvW6MwI6FmuzEImOaIMsI8fi1nCa4cGAmOuWvMzxPuFjWjXSyZNUhT40GvBLjookF6jjG1KZjWQERyVcZAP2vEqtIiNwyxrOpxJMPs8EeUwv6PAmRafKoALhkTvZQpiLcv3hMJmEWZ68lQz9bmvMQEsJGgLyFQeoQqaA/IatfhqAHV2079haGxgVJC17t5ZSvgQx2h3riclzAh1ZhKoiw9vPw1WD31GmMDsrVQVJGs18/5TnGcwmp5FyH9YmrhLzGCI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/pyTibber
